import 'material-icons/iconfont/material-icons.css'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import localForage from 'localforage'
import randomString from 'random-string'

import styles from '../styles/Home.module.css'

export default function Home() {
	const [userCode, setUserCode] = useState('')
	const [themeToggle, setThemeToggle] = useState(false)
	const [textType, setTextType] = useState('text')
	const [userId, setUserId] = useState('')
	const [error, setError] = useState('')
	const [success, setSuccess] = useState('')
	const [search, setSearch] = useState('')
	const toggleTheme = () => {
		setThemeToggle(!themeToggle)
	}

	const handleSelectChange = (e) => {
		localStorage.setItem('textType', e.target.value)
		setTextType(e.target.value)
	}

	const handleSaveUserInput = async (e) => {
		try {
			if (userCode !== '') {
				setUserId('')
				setSearch('')
				const userNote = {
					userCode,
					textType
				}
				const key =
					userNote.userCode.slice(0, 1) +
					userNote.textType +
					randomString({ length: 5 })
				setUserId(key)
				await localForage.setItem(key, userNote)
				setUserCode('')
				setSuccess('Saved!')
			}
		} catch (error) {
			console.error(error)
			setError('Error saving note')
		}
	}

	const handleFindNote = async (e) => {
		try {
			if ((e.key === 'Enter' || e.keyCode === 13) && e.target.value !== '') {
				const data = await localForage.getItem(e.target.value)
				if (!data) {
					return setError('No note found with that Id')
				}
				setTextType(data.textType)
				setUserCode(data.userCode)
				setUserId(e.target.value)
				setSearch('')
				setSuccess('Note found')
			}
		} catch (error) {
			console.error(error)
			setError('No note found with that Id')
		}
	}

	const handleCopyToClipboard = () => {
		navigator.clipboard.writeText(userId)
		setSuccess('Copied to clipboard')
	}

	useEffect(() => {
		const themeState = localStorage.getItem('theme')
		if (themeState) setThemeToggle(true)
	}, [])

	useEffect(() => {
		if (themeToggle) {
			document.body.classList.add('dark')
			document.getElementById('title').classList.add('dark')
			document.getElementById('addTextCode').classList.add('dark')
			document.getElementById('textType').classList.add('dark')
			document.getElementById('nodeId').classList.add('dark')
			document.getElementById('pushBtn').classList.add('dark')
			localStorage.setItem('theme', 'dark')
		} else {
			document.body.classList.remove('dark')
			document.getElementById('title').classList.remove('dark')
			document.getElementById('addTextCode').classList.remove('dark')
			document.getElementById('textType').classList.remove('dark')
			document.getElementById('nodeId').classList.remove('dark')
			document.getElementById('pushBtn').classList.remove('dark')
			localStorage.removeItem('theme')
		}
	}, [themeToggle])

	useEffect(() => {
		const errorTimeout = setTimeout(() => {
			setError('')
		}, 3000)

		return () => {
			clearTimeout(errorTimeout)
		}
	}, [error])

	useEffect(() => {
		const successTimeout = setTimeout(() => {
			setSuccess('')
		}, 3000)
		return () => {
			clearTimeout(successTimeout)
		}
	}, [success])

	return (
		<div className={styles.container}>
			<Head>
				<title>Save Text Code Snippets</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<section className={styles.themeWrapper}>
				<span
					className={`${styles.themeIcon}
						 material-icons${themeToggle ? '-outlined' : ''}`}
					onClick={toggleTheme}
				>
					dark_mode
				</span>
			</section>
			<main className={styles.main}>
				<h1 className={styles.title} id='title'>
					Save Text Code Snippets
				</h1>
				{userId && (
					<h5 id='title'>
						Save this ID somewhere to access the notes later
						<span className={styles.userDisplayId}>
							{userId}
							<span
								className={`${styles.copyIcon}
						 material-icons${themeToggle ? '-outlined' : ''}`}
								onClick={handleCopyToClipboard}
							>
								file_copy
							</span>
						</span>
					</h5>
				)}
				<section>
					<div className={styles.noteSearchBox}>
						<input
							type='text'
							name='noteId'
							id='nodeId'
							placeholder='Enter your Note ID here...'
							onKeyDown={handleFindNote}
							onBlur={handleFindNote}
							value={search}
							onChange={(e) => setSearch(e.target.value)}
						/>
					</div>
				</section>
				<section className={styles.toolKit_wrapper}>
					<select
						id='textType'
						onChange={handleSelectChange}
						value={textType}
						className={styles.select}
					>
						<option value='text'>Text</option>
						<option value='code'>Code</option>
					</select>
					<div>
						{error && <h5 className={styles.error}>{error}</h5>}
						{success && <h5 className={styles.success}>{success}</h5>}
					</div>
				</section>
				<textarea
					name='addTextCode'
					id='addTextCode'
					cols='60'
					rows='10'
					placeholder='Enter your code or text here'
					value={userCode}
					className={styles.textarea}
					autoComplete='off'
					autoCorrect='on'
					onChange={(e) => setUserCode(e.target.value)}
				></textarea>
				<button
					className={styles.button}
					name='pushBtn'
					id='pushBtn'
					onClick={handleSaveUserInput}
				>
					Push Inn
				</button>
			</main>
			<footer className={styles.footer}>
				<h5>Made in ❤️ with JS React Next & Vercel</h5>
				<blockquote>Aditya 2022 - Infinity</blockquote>
			</footer>
		</div>
	)
}
