import 'material-icons/iconfont/material-icons.css'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
	const [userCode, setUserCode] = useState('')
	const [themeToggle, setThemeToggle] = useState(false)

	const toggleTheme = () => {
		setThemeToggle(!themeToggle)
	}

	useEffect(() => {
		if (themeToggle) {
			document.body.classList.add('dark')
			document.getElementById('title').classList.add('dark')
			document.getElementById('addTextCode').classList.add('dark')
		} else {
			document.body.classList.remove('dark')
			document.getElementById('title').classList.remove('dark')
			document.getElementById('addTextCode').classList.remove('dark')
		}
	}, [themeToggle])

	return (
		<div className={styles.container}>
			<Head>
				<title>Save Text Code Snippets</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title} id='title'>
					Save Text Code Snippets
				</h1>
				<section>
					<span
						className={
							themeToggle
								? 'material-icons-outlined themeIcon'
								: 'material-icons themeIcon'
						}
						onClick={toggleTheme}
					>
						dark_mode
					</span>
				</section>
				<textarea
					name='addTextCode'
					id='addTextCode'
					cols='60'
					rows='10'
					placeholder='Enter your code or text here'
					onChange={(e) => setUserCode(e.target.value)}
					value-={userCode}
					className={styles.textarea}
				></textarea>
			</main>
		</div>
	)
}
